[package]
name = "patronus"
version = "0.34.0"
description = "Hardware bug-finding toolkit."
homepage = "https://kevinlaeufer.com"
keywords = ["RTL", "btor", "model-checking", "SMT", "bit-vector"]
edition.workspace = true
authors.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
indexmap = "2.7.0"
codespan-reporting = "0.11.1"
lazy_static = "1.4.0"
smallvec = { version = "1.x", features = ["union"] }
rand = { version = "0.9", features = ["small_rng"] }
boolean_expression.workspace = true
regex.workspace = true
baa.workspace = true
rustc-hash.workspace = true
thiserror.workspace = true
cranelift = { version = "0.124.1", features = ["module", "jit"] }
inventory = "0.3.20"
fixedbitset = "0.5.7"
paste = "1.0.15"
log = "0.4.28"
dot-writer = { version = "0.1.4", optional = true }
cranelift-reader = { version = "0.124.2", optional = true }
walkdir = { version = "2.5.0", optional = true }
delegate = { version = "0.13.4", optional = true }

[dev-dependencies]
insta = { version = "1.x", features = ["yaml"] }

[features]
trace = []
visualize = ["dot-writer"]
aot-clif = ["cranelift-reader", "delegate", "walkdir"]
inline = []
